{{- if .Values.image.pullSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  labels:
{{ include "azure-pipelines-agent.labels" . | indent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}