replicaCount: 2

image:
  repository: silentreatmen7/kube-azure-agent
  pullPolicy: Always
  tag: latest
  pullSecret:
    create: True
    registry: ""
    username: ""
    password: ""
    email: devops@azure.io

pipelines:
  url: ""
  pat:
    value: ""
  pool: ""
  agent:
    name: "azagent"
    mountDocker: true
    workDir: "_work"

serviceAccount:
  create: true
  clusterAdmin: true
  name: azadmin

imagePullSecrets: 
- name: regcred

